apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01USXpNREV3TlRBek5Gb1hEVE13TVRJeU9ERXdOVEF6TkZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS2V5CnZIQ2tBdEpNbXNvWVJjeEZaOXltdlF3M1c2NElVRmdHUldrSHkzOUNCeE5QeW9EZ09Pa04zZ0tVVjUrMGpiNzEKOHFsSUZWeWp1Y0pLR1IrZ2VLamZSYnB0QWpsLzR0alBYeE8yMnkvOWx2UE80WmRobmJvUVd6RXBvQnFKb1Y2NApmcTZjNFBBRWlqN25nY25oNVQvbHVqQUxiOFEwUWhVdDVoa3UwTGdRSkQ3QngrcHN2cUc1blVoRk8wMGVTa3U2Clo5bFcxUU52U0JLR21UTXA3bGxtNUdOb1ZmZnd5emlHNFcvSE9sOVkvcGh2STJYY0trVGNkem1MSEs4bHY4aDkKNUNLQng2QUtFWC8yWVA4SCtRMkppRFhFSjkzaC9rcjgwVW9GTThBTTZSWnZBUGYyTm1vS2VLUU1LM3lzUWhOSgprSzUxT1pqT3Y4RWI0c0pXUnpFQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFHd0tlR1FSb2NmTFFWazZSc1g5U05pdy93c0YKYlJONURwbzVaMjAvS01Va3lUTytzU1E1azhDZWlyT293dkFNQmJWTnZ6UHI5MWRRRUUzaGw2cUhhN1ljOXAxWApyOXZCM0NjMWg0cEZaWlVlK0pUdEFXQ0ZGV2t2QzNjUUZWQlh4YTlPblRpbXRObmhXV1VyTmx0YVVJdVVndG5ICmhGM253WklpV284NENMWFhrTTdVQTlDY0lETmdrK3JrdVpxSi9La1hPVmIyWXFyTEcyVlBZaG1iL0V1RVhUekIKb1kra015cUpZK1hWcTVIUkxkcDJ3NnpaZm9HQUxrelpxNXF6bGNLS0J2eWtJckMvSEJWLzI5N0piMVppREtFegpKRzBSaE5KOEhJbE1tTHhvYzluMi83dEZyeWp6VzI1Y3BmVTJVb3RRc0V4U1I1MXpQY005ZFVpZ3ZGRT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://5881C7FA84789E1C1FF88A6655B4BCFB.gr7.eu-central-1.eks.amazonaws.com
  name: arn:aws:eks:eu-central-1:215684182694:cluster/udagram-eseidinger-dev
contexts:
- context:
    cluster: arn:aws:eks:eu-central-1:215684182694:cluster/udagram-eseidinger-dev
    user: arn:aws:eks:eu-central-1:215684182694:cluster/udagram-eseidinger-dev
  name: arn:aws:eks:eu-central-1:215684182694:cluster/udagram-eseidinger-dev
current-context: arn:aws:eks:eu-central-1:215684182694:cluster/udagram-eseidinger-dev
kind: Config
preferences: {}
users:
- name: arn:aws:eks:eu-central-1:215684182694:cluster/udagram-eseidinger-dev
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "udagram-eseidinger-dev"
        # - "-r"
        # - "<role-arn>"
      # env:
        # - name: AWS_PROFILE
        #   value: "<aws-profile>"