version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: eseidinger/reverseproxy:main
  backend_user:
    build:
      context: ../../udacity-c3-restapi-user
    image: eseidinger/udacity-restapi-user:main
  backend_feed:
    build:
      context: ../../udacity-c3-restapi-feed  
    image: eseidinger/udacity-restapi-feed:main
  frontend:
    build:
      context: ../../udacity-c3-frontend  
    image: eseidinger/udacity-frontend:main
